### ISSUE TITLE
incorrect authors and artist in bot info json

### ISSUE THREAD

**Issue by SilviasUk** [juaneth/Entity#1]
Cool idea, don't understand how it works xD but sure, btw I was looking in ./entity-bot/config/info.JSON
it says spoon (as the artist) if you want you can remove me too, just an FYI xD

**Comment by SilviasUk** [comment]
oop, didn't mean to make it a issue

**Comment by juaneth** [comment]
sure will do, you did technically write most of the code so ill keep you in there

**Comment by juaneth** [comment]
if you want to edit something, you can fork this, change something, then pull request. ill read it and make a few modifications and then its applied
